---

- name: deploy ec2 instance
  ec2:
    region: eu-west-2
    key_name: rob-laptop
    instance_type: t2.micro
    image: ami-e7d6c983
    wait: yes
    count: 1
    vpc_subnet_id: subnet-b20918ca
    assign_public_ip: yes
    instance_tags:
      Name: selinux-test
      Role: testing

- name: wait for ec2 instance to come online
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
    delay: 10
    timeout: 300
  connection: local
