---

- name: deploy ec2 instance
  ec2:
    region: eu-west-2
    key_name: ansible-master@aws
    instance_type: t2.micro
    image: ami-e7d6c983
    wait: true
    exact_count: "{{ count }}"
    vpc_subnet_id: subnet-b20918ca
    assign_public_ip: true
    instance_tags:
      Name: zabbix-server
      Role: testing
      Creator: Rob Pickerill
      Reason: training
      Tool: ansible
    count_tag:
      Name: zabbix-server
  register: ec2

- name: debug ec2
  debug:
    var: ec2.tagged_instances
    verbosity: 1

- name: add instances to zabbix-server group
  add_host:
    hostname: "{{ item.public_dns_name }}"
    groupname: zabbix-server
  with_items: "{{ ec2.tagged_instances }}"

- name: wait for ec2 instance to come online
  wait_for:
    port: 22
    host: '{{ item.public_dns_name }}'
    search_regex: OpenSSH
    delay: 1
    timeout: 300
  connection: local
  with_items: "{{ ec2.tagged_instances }}"
