---

- name: deploy ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  remote_user: ec2-user

  roles:
    - deploy
  tags:
    - deploy

- name: deploy zabbix server
  hosts: tag_Name_zabbix_server
  become: true
  remote_user: ec2-user

  roles:
    - zabbix-server
  tags:
    - zabbix-server
