---

- name: deploy ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  remote_user: ec2-user

  roles:
    - deploy
  tags:
    - deploy

- name: deploy zabbix server
  hosts: zabbix-server
  become: true
  become_user: root
  remote_user: ec2-user

  roles:
    - zabbix-server
  tags:
    - zabbix-server
