---

- name: install zabbix-agent
  yum:
    name: zabbix-agent
    state: present

- name: copy zabbix-agent config
  template:
    src: agent/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0660
  notify: restart zabbix agent

- name: start zabbix agent
  service:
    name: zabbix-agent
    state: started
    enabled: true

- meta: flush_handlers

- name: wait for zabbix-agent
  wait_for:
    port: 10050
