---

mariadb_release: 10.2
 
mariadb_gpg_keys:
  - https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

mariadb_packages:
  - MariaDB-server
  - MariaDB-client
  - MySQL-python27

mariadb_port: 3306

zabbix_release: 3.4

zabbix_repos:
  zabbix-official:
    desc: zabbix-official/{{ zabbix_release }}
    baseurl: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/6/$basearch/ 
  zabbix-deprecated:
    desc: zabbix-deprecated/{{ zabbix_release }}
    baseurl: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/6/$basearch/deprecated/
    enabled: false
  zabbix-nonsupported:
    desc: zabbix-nonsupported/{{ zabbix_release }}
    baseurl: http://repo.zabbix.com/non-supported/rhel/6/$basearch/
 
zabbix_gpg_keys:
  - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
  - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-79EA5ED4
  - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591-EL5
  - https://repo.zabbix.com/zabbix-official-repo.key

zabbix_packages:
  - zabbix-server-mysql
  - zabbix-agent
  - zabbix-sender
  - zabbix-get

zabbix_admin_passwd: GkcRWWk
mariadb_root_passwd: cU1TD1RoU6JsuSCb8Ve+RWjuaKcaZTbAvCGUiIgCv9o=
mariadb_zabbix_passwd: 59J7xgdBeXZf6aA3IybYbd7j3nDkVm+Cvb7KGim300U= 

web_packages:
  - zabbix-web-mysql
  - httpd24
  - php71
  - php71-bcmath
  - php71-gd
  - php71-mbstring
  - php71-ldap
  - php71-mysqlnd
  - php71-opcache

zabbix_frontend_ports:
  - 80
  - 443

zabbix_server_ports:
  - 10051

zabbix_agent_ports:
  - 10050
