---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: zabbix-server
    image: ami-e7d6c983
    instance_type: t2.micro
    vpc_subnet_id: subnet-b20918ca
    key_name: ansible-master@aws
    region: eu-west-2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
